---
title: 'Practical ML: Prediction Assignment'
output: html_document
---

## Load Libraries

```{r libs, echo=TRUE}
library(lattice)
library(ggplot2)
library(caret)
library(randomForest)
library(rpart)
library(rpart.plot)
set.seed(1234)
```

## Load Data
```{r data, echo=TRUE}
trainset <- read.csv("pml-training.csv", na.strings=c("NA","#DIV/0!", ""))
testset <- read.csv("pml-testing.csv", na.strings=c("NA","#DIV/0!", ""))
```

## Exploratory Analysis
### Training Data
```{r train, echo=TRUE}
dim(trainset)
summary(trainset)
```

### Testing Data
```{r test, echo=TRUE}
dim(testset)
summary(testset)
```

## Data Preprocessing
Remove NULL values
```{r prep, echo=TRUE}
trainset <- trainset[,colSums(is.na(trainset)) == 0]
testset <- testset[,colSums(is.na(testset)) == 0]
```

Remove redundant variables
```{r redun, echo=TRUE}
trainset <- trainset[,-c(1:7)]
testset <- testset[,-c(1:7)]
```

### Data Partition
```{r part, echo=TRUE}
trainingset <- createDataPartition(y=trainset$classe, p=0.75, list=FALSE)
finaltrainset <- trainset[trainingset, ] 
finaldevset <- trainset[-trainingset, ]
finaltrainset
finaldevset
```

### Plot data distribution
```{r distr, echo=TRUE}
plot(as.factor(finaltrainset$classe), col="blue", main="Bar Plot of levels of the variable classe within the subTraining data set", xlab="classe levels", ylab="Frequency")
```

## Model Selection
### Decision Tree
```{r desct, echo=TRUE}
model1 <- rpart(classe ~ ., data=finaltrainset, method="class")
prediction1 <- predict(model1, finaldevset, type = "class")
rpart.plot(model1, main="Classification Tree", extra=102, under=TRUE, faclen=0)
confusionMatrix(factor(prediction1), factor(finaldevset$classe))
model1$finalModel
```

### Random Forest
```{r randf, echo=TRUE}
model2 <- randomForest(as.factor(classe) ~ ., data=finaltrainset, method="class")
prediction2 <- predict(model2, finaldevset, type = "class")
confusionMatrix(as.factor(prediction2), as.factor(finaldevset$classe))
```

### Final Prediction on Test Set
```{r tests, echo=TRUE}
finalpredict <- predict(model2, testset, type="class")
finalpredict
```
